services:
  userbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the session file for persistence
      - ./sessions:/app/sessions
      # ✅ ДОБАВИТЬ ПАПКУ С МОДЕЛЬЮ
      - ./models:/app/models
    environment:
      - SESSION_NAME=/app/sessions/userbot
    env_file:
      - .env
    restart: unless-stopped